# -*- coding: utf-8 -*-
"""calculadora exercicio corrigido.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1usd7k1o9uMP6kVkgVA0yTnmOX8vDorCC
"""

def calculadora():
    while True:
        num1 = input("Digite o primeiro número: ")
        num2 = input("Digite o segundo número: ")


        try:
            num1 = float(num1)
            num2 = float(num2)
        except ValueError:
            print("Por favor, insira números válidos.")
            continue


        soma = num1 + num2
        subtracao = num1 - num2
        multiplicacao = num1 * num2
        divisao = num1 / num2


        print(f"Soma: {soma}")
        print(f"Subtração: {subtracao}")
        print(f"Multiplicação: {multiplicacao}")
        print(f"Divisão: {divisao}")


        continuar = input("Deseja realizar outra operação? (s/n): ")
        if continuar.lower() != 's':
            print("Obrigado por usar a calculadora!")
            break

calculadora()